In [ ]:
- Note: This dataset is synthetic and does not represent real-world
- healthcare records. The analysis results should not be interpreted
- as actual healthcare statistics or used for real-world decisions.

## Extract

In [1]:
import pandas as pd

In [ ]:
pip install pandas sqlalchemy pyodbc

In [3]:
df = pd.read_csv("healthcare_dataset.csv")

In [4]:
df

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
0,Bobby JacksOn,30,Male,B-,Cancer,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.281306,328,Urgent,2024-02-02,Paracetamol,Normal
1,LesLie TErRy,62,Male,A+,Obesity,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.327287,265,Emergency,2019-08-26,Ibuprofen,Inconclusive
2,DaNnY sMitH,76,Female,A-,Obesity,2022-09-22,Tiffany Mitchell,Cook PLC,Aetna,27955.096079,205,Emergency,2022-10-07,Aspirin,Normal
3,andrEw waTtS,28,Female,O+,Diabetes,2020-11-18,Kevin Wells,"Hernandez Rogers and Vang,",Medicare,37909.782410,450,Elective,2020-12-18,Ibuprofen,Abnormal
4,adrIENNE bEll,43,Female,AB+,Cancer,2022-09-19,Kathleen Hanna,White-White,Aetna,14238.317814,458,Urgent,2022-10-09,Penicillin,Abnormal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55495,eLIZABeTH jaCkSOn,42,Female,O+,Asthma,2020-08-16,Joshua Jarvis,Jones-Thompson,Blue Cross,2650.714952,417,Elective,2020-09-15,Penicillin,Abnormal
55496,KYle pEREz,61,Female,AB-,Obesity,2020-01-23,Taylor Sullivan,Tucker-Moyer,Cigna,31457.797307,316,Elective,2020-02-01,Aspirin,Normal
55497,HEATher WaNG,38,Female,B+,Hypertension,2020-07-13,Joe Jacobs DVM,"and Mahoney Johnson Vasquez,",UnitedHealthcare,27620.764717,347,Urgent,2020-08-10,Ibuprofen,Abnormal
55498,JENniFER JOneS,43,Male,O-,Arthritis,2019-05-25,Kimberly Curry,"Jackson Todd and Castro,",Medicare,32451.092358,321,Elective,2019-05-31,Ibuprofen,Abnormal
55499,jAMES GARCiA,53,Female,O+,Arthritis,2024-04-02,Dennis Warren,Henry Sons and,Aetna,4010.134172,448,Urgent,2024-04-29,Ibuprofen,Abnormal

## Explore and Transform

In [5]:
df.dtypes

Name                   object
Age                     int64
Gender                 object
Blood Type             object
Medical Condition      object
Date of Admission      object
Doctor                 object
Hospital               object
Insurance Provider     object
Billing Amount        float64
Room Number             int64
Admission Type         object
Discharge Date         object
Medication             object
Test Results           object
dtype: object

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 55500 entries, 0 to 55499
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Name                55500 non-null  object
 1   Age                 55500 non-null  int64
 2   Gender              55500 non-null  object
 3   Blood Type          55500 non-null  object
 4   Medical Condition   55500 non-null  object
 5   Date of Admission   55500 non-null  object
 6   Doctor              55500 non-null  object
 7   Hospital            55500 non-null  object
 8   Insurance Provider  55500 non-null  object
 9   Billing Amount      55500 non-null  float64
 10  Room Number         55500 non-null  int64
 11  Admission Type      55500 non-null  object
 12  Discharge Date      55500 non-null  object
 13  Medication          55500 non-null  object
 14  Test Results        55500 non-null  object
dtypes: float64(1), int64(2), object(12)
memory usage: 6.4+ MB

In [7]:
df.shape

(55500, 15)

In [8]:
df.duplicated().sum()

534

In [9]:
df = df.drop_duplicates()

In [10]:
df.shape

(54966, 15)

In [11]:
df.isnull().sum()

Name                  0
Age                   0
Gender                0
Blood Type            0
Medical Condition     0
Date of Admission     0
Doctor                0
Hospital              0
Insurance Provider    0
Billing Amount        0
Room Number           0
Admission Type        0
Discharge Date        0
Medication            0
Test Results          0
dtype: int64

In [ ]:
df['Date of Admission'] = pd.to_datetime(df['Date of Admission'])
df['Discharge Date'] = pd.to_datetime(df['Discharge Date'])

In [ ]:
df['Length of Stay'] = (
    df['Discharge Date'] - df['Date of Admission']
).dt.days

In [14]:
df

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results,Length of Stay
0,Bobby JacksOn,30,Male,B-,Cancer,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.281306,328,Urgent,2024-02-02,Paracetamol,Normal,2
1,LesLie TErRy,62,Male,A+,Obesity,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.327287,265,Emergency,2019-08-26,Ibuprofen,Inconclusive,6
2,DaNnY sMitH,76,Female,A-,Obesity,2022-09-22,Tiffany Mitchell,Cook PLC,Aetna,27955.096079,205,Emergency,2022-10-07,Aspirin,Normal,15
3,andrEw waTtS,28,Female,O+,Diabetes,2020-11-18,Kevin Wells,"Hernandez Rogers and Vang,",Medicare,37909.782410,450,Elective,2020-12-18,Ibuprofen,Abnormal,30
4,adrIENNE bEll,43,Female,AB+,Cancer,2022-09-19,Kathleen Hanna,White-White,Aetna,14238.317814,458,Urgent,2022-10-09,Penicillin,Abnormal,20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55495,eLIZABeTH jaCkSOn,42,Female,O+,Asthma,2020-08-16,Joshua Jarvis,Jones-Thompson,Blue Cross,2650.714952,417,Elective,2020-09-15,Penicillin,Abnormal,30
55496,KYle pEREz,61,Female,AB-,Obesity,2020-01-23,Taylor Sullivan,Tucker-Moyer,Cigna,31457.797307,316,Elective,2020-02-01,Aspirin,Normal,9
55497,HEATher WaNG,38,Female,B+,Hypertension,2020-07-13,Joe Jacobs DVM,"and Mahoney Johnson Vasquez,",UnitedHealthcare,27620.764717,347,Urgent,2020-08-10,Ibuprofen,Abnormal,28
55498,JENniFER JOneS,43,Male,O-,Arthritis,2019-05-25,Kimberly Curry,"Jackson Todd and Castro,",Medicare,32451.092358,321,Elective,2019-05-31,Ibuprofen,Abnormal,6
55499,jAMES GARCiA,53,Female,O+,Arthritis,2024-04-02,Dennis Warren,Henry Sons and,Aetna,4010.134172,448,Urgent,2024-04-29,Ibuprofen,Abnormal,27

In [ ]:
df['Name'] = df['Name'].str.title()

In [16]:
df['Age'].describe()

count    54966.000000
mean        51.535185
std         19.605661
min         13.000000
25%         35.000000
50%         52.000000
75%         68.000000
max         89.000000
Name: Age, dtype: float64

In [17]:
df["Gender"].unique()

array(['Male', 'Female'], dtype=object)

In [18]:
df["Blood Type"].unique()

array(['B-', 'A+', 'A-', 'O+', 'AB+', 'AB-', 'B+', 'O-'], dtype=object)

In [19]:
df["Medical Condition"].unique()

array(['Cancer', 'Obesity', 'Diabetes', 'Asthma', 'Hypertension',
       'Arthritis'], dtype=object)

In [20]:
df["Doctor"].sample(20)

25275         Krystal Dixon
54861            Lisa Jones
10016         Joshua Watson
10770           Kevin Davis
19036       Sharon Franklin
22800        Allison Carter
17380        Victor Sanders
17138       Richard Griffin
52525        Anthony Kramer
29861         James Herring
73               Raven Wong
29494       Ashley Chambers
6599     Mr. Ryan Adams DDS
20092          Ashley Lewis
48216             John Cruz
30192          Julia Valdez
21767    Christopher Wright
4833     Christopher Morgan
26142      Anthony Martinez
5371      Michelle Sullivan
Name: Doctor, dtype: object

In [21]:
df["Doctor"].value_counts()

Doctor
Michael Smith      27
John Smith         22
Robert Smith       21
James Smith        20
Michael Johnson    20
                   ..
Shane Tate          1
Christy Parker      1
Larry Miller        1
Chelsea Neal        1
Jeffrey Moore       1
Name: count, Length: 40341, dtype: int64

In [22]:
df["Hospital"].sample(20)

13595         Lyons and Foster Rodgers,
9841      Anderson and Sullivan Rivera,
28212          Lopez, Jones Schmidt and
12503                   Mcguire-Johnson
12890              Hale, Lowe Gates and
2914                       Wright Group
31362                         Ltd Clark
39055            Wells Roberts, and Lee
36191                          Le-Henry
15693          and Dennis Ross Hopkins,
7420          and Bowers Morrow Conrad,
29182                     Rodgers-Davis
43989          and Adams Martin, Thomas
3896        and Richards Barrera, Olson
42130      and Matthews, Wright Lambert
22849                     Wilson-Taylor
51273                   Johnson-Andrade
16508                      Hill-Gilbert
23269    Cunningham Burke and Ferguson,
52834                          PLC Hart
Name: Hospital, dtype: object

In [23]:
df["Hospital"].value_counts()

Hospital
LLC Smith                       44
Ltd Smith                       39
Johnson PLC                     37
Smith Ltd                       37
Smith Group                     36
                                ..
PLC Navarro                      1
PLC Mcintosh                     1
and Hernandez, Hughes Walton     1
Myers-Williams                   1
Moreno Murphy, Griffith and      1
Name: count, Length: 39876, dtype: int64

In [24]:
df["Insurance Provider"].unique()

array(['Blue Cross', 'Medicare', 'Aetna', 'UnitedHealthcare', 'Cigna'],
      dtype=object)

In [25]:
df['Billing Amount'].describe()

count    54966.000000
mean     25544.306284
std      14208.409711
min      -2008.492140
25%      13243.718641
50%      25542.749145
75%      37819.858159
max      52764.276736
Name: Billing Amount, dtype: float64

In [26]:
negative_billing = df[df['Billing Amount'] < 0]
len(negative_billing)

106

In [27]:
negative_billing = df[df['Billing Amount'] < 0]

negative_billing.head(20)

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results,Length of Stay
132,Ashley Erickson,32,Female,AB-,Cancer,2019-11-05,Gerald Hooper,"and Johnson Moore, Branch",Aetna,-502.507813,376,Urgent,2019-11-23,Penicillin,Normal,18
799,Christopher Weiss,49,Female,AB-,Asthma,2023-02-16,Kelly Thompson,Hunter-Hughes,Aetna,-1018.245371,204,Elective,2023-03-09,Penicillin,Inconclusive,21
1018,Ashley Warner,60,Male,A+,Hypertension,2021-12-21,Andrea Bentley,"and Wagner, Lee Klein",Aetna,-306.364925,426,Elective,2022-01-11,Ibuprofen,Normal,21
1421,Jay Galloway,74,Female,O+,Asthma,2021-01-20,Debra Everett,Group Peters,Blue Cross,-109.097122,381,Emergency,2021-02-09,Ibuprofen,Abnormal,20
2103,Joshua Williamson,72,Female,B-,Diabetes,2021-03-21,Wendy Ramos,"and Huff Reeves, Dennis",Blue Cross,-576.727907,369,Urgent,2021-04-17,Aspirin,Abnormal,27
2696,Scott Vazquez,74,Male,B+,Diabetes,2023-04-12,Edward Yates,James Ltd,Medicare,-135.986000,445,Elective,2023-05-03,Ibuprofen,Abnormal,21
2855,Carol Anderson,39,Female,B-,Hypertension,2020-04-03,Dr. Patrick Hines,"Carter Carter, and Patterson",Blue Cross,-370.983674,203,Elective,2020-04-10,Ibuprofen,Abnormal,7
3772,Mr. Christopher Alvarado,77,Male,AB+,Obesity,2022-06-03,Mr. Dean Guzman DDS,Johnson Inc,Blue Cross,-1310.272895,257,Elective,2022-06-13,Paracetamol,Inconclusive,10
5445,Alexandra Khan,32,Male,AB+,Arthritis,2022-07-14,Michael Vaughn,"Bowen Lopez, and Terry",Aetna,-692.408820,372,Elective,2022-07-19,Lipitor,Abnormal,5
5708,Joseph Cox,23,Male,AB-,Diabetes,2019-10-13,Peter Smith,Inc Ward,Blue Cross,-353.865186,271,Elective,2019-10-25,Lipitor,Inconclusive,12
6336,Mitchell Maldonado,41,Female,A+,Asthma,2022-06-22,Melissa Woods,Richardson-Bennett,Medicare,-378.960784,414,Urgent,2022-06-30,Lipitor,Inconclusive,8
6596,Julie Christian,28,Female,AB+,Diabetes,2019-06-30,Kathryn Ray,Group Mcconnell,Cigna,-367.203959,387,Urgent,2019-07-09,Lipitor,Normal,9
6798,Alexander Gardner,45,Male,AB-,Cancer,2023-03-23,Tracy Brown,Maldonado Group,Cigna,-198.283806,329,Elective,2023-04-09,Aspirin,Abnormal,17
6961,Angela Allen,83,Female,B-,Diabetes,2019-08-21,Robert Kennedy,"Brown and Randolph, Young",Cigna,-43.098522,189,Urgent,2019-08-24,Penicillin,Abnormal,3
8757,Alan Scott,48,Female,A-,Asthma,2019-10-23,Jacob Kirby,Lopez-Hughes,Medicare,-857.125933,309,Urgent,2019-11-18,Paracetamol,Abnormal,26
10245,Brandon Hall,27,Male,B+,Hypertension,2020-01-29,Cindy Smith,Sons and Evans,Aetna,-155.082020,368,Urgent,2020-02-01,Aspirin,Abnormal,3
10516,Lucas Sullivan,31,Female,A-,Obesity,2022-04-05,Brenda Burke,Sons and Harris,UnitedHealthcare,-211.723845,496,Emergency,2022-04-11,Aspirin,Abnormal,6
10736,Rebecca Cline,39,Female,B+,Asthma,2020-05-07,Rebecca Miller,"Stout Dougherty, and Washington",Cigna,-656.153072,195,Emergency,2020-05-17,Ibuprofen,Abnormal,10
10768,Valerie Allen,82,Female,B-,Diabetes,2021-02-05,Judy Massey,"Hebert, Brown Kim and",Medicare,-227.995064,118,Urgent,2021-02-25,Aspirin,Inconclusive,20
12074,Brian Young,85,Male,O-,Cancer,2021-04-13,Dr. Jenna Caldwell,Hampton LLC,Cigna,-147.072199,133,Emergency,2021-04-20,Aspirin,Abnormal,7

In [ ]:
# Data Quality Check — Billing Amount

#106 records contain negative billing amounts.Therefore, these records will be removed.

df.drop(
    df[df['Billing Amount'] < 0].index,
    inplace=True
)

In [29]:
df['Billing Amount'].min()

9.238787497393332

In [30]:
df['Room Number'].describe()

count    54860.000000
mean       301.109752
std        115.217195
min        101.000000
25%        202.000000
50%        302.000000
75%        400.000000
max        500.000000
Name: Room Number, dtype: float64

In [31]:
df["Admission Type"].unique()

array(['Urgent', 'Emergency', 'Elective'], dtype=object)

In [32]:
df["Medication"].unique()

array(['Paracetamol', 'Ibuprofen', 'Aspirin', 'Penicillin', 'Lipitor'],
      dtype=object)

In [33]:
df["Test Results"].unique()

array(['Normal', 'Inconclusive', 'Abnormal'], dtype=object)

In [34]:
df["Length of Stay"].describe()

count    54860.000000
mean        15.498815
std          8.661357
min          1.000000
25%          8.000000
50%         15.000000
75%         23.000000
max         30.000000
Name: Length of Stay, dtype: float64

In [35]:
df.insert(0, 'Admission_ID', range(1, len(df) + 1))

In [36]:
df

,Admission_ID,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results,Length of Stay
0,1,Bobby Jackson,30,Male,B-,Cancer,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.281306,328,Urgent,2024-02-02,Paracetamol,Normal,2
1,2,Leslie Terry,62,Male,A+,Obesity,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.327287,265,Emergency,2019-08-26,Ibuprofen,Inconclusive,6
2,3,Danny Smith,76,Female,A-,Obesity,2022-09-22,Tiffany Mitchell,Cook PLC,Aetna,27955.096079,205,Emergency,2022-10-07,Aspirin,Normal,15
3,4,Andrew Watts,28,Female,O+,Diabetes,2020-11-18,Kevin Wells,"Hernandez Rogers and Vang,",Medicare,37909.782410,450,Elective,2020-12-18,Ibuprofen,Abnormal,30
4,5,Adrienne Bell,43,Female,AB+,Cancer,2022-09-19,Kathleen Hanna,White-White,Aetna,14238.317814,458,Urgent,2022-10-09,Penicillin,Abnormal,20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55495,54856,Elizabeth Jackson,42,Female,O+,Asthma,2020-08-16,Joshua Jarvis,Jones-Thompson,Blue Cross,2650.714952,417,Elective,2020-09-15,Penicillin,Abnormal,30
55496,54857,Kyle Perez,61,Female,AB-,Obesity,2020-01-23,Taylor Sullivan,Tucker-Moyer,Cigna,31457.797307,316,Elective,2020-02-01,Aspirin,Normal,9
55497,54858,Heather Wang,38,Female,B+,Hypertension,2020-07-13,Joe Jacobs DVM,"and Mahoney Johnson Vasquez,",UnitedHealthcare,27620.764717,347,Urgent,2020-08-10,Ibuprofen,Abnormal,28
55498,54859,Jennifer Jones,43,Male,O-,Arthritis,2019-05-25,Kimberly Curry,"Jackson Todd and Castro,",Medicare,32451.092358,321,Elective,2019-05-31,Ibuprofen,Abnormal,6
55499,54860,James Garcia,53,Female,O+,Arthritis,2024-04-02,Dennis Warren,Henry Sons and,Aetna,4010.134172,448,Urgent,2024-04-29,Ibuprofen,Abnormal,27

## Loading

In [ ]:
from sqlalchemy import create_engine
import urllib

params = urllib.parse.quote_plus(
    "DRIVER={ODBC Driver 18 for SQL Server};"
    "SERVER=YOUR_SERVER;"
    "DATABASE=YOUR_DATABASE;"
    "Trusted_Connection=yes;"
    "TrustServerCertificate=yes;"
)

engine = create_engine(
    f"mssql+pyodbc:///?odbc_connect={params}"
)

In [40]:
with engine.connect() as connection:
    print("Connected successfully!")

Connected successfully!

In [ ]:
df.to_sql(
    name='healthcare_admissions',
    con=engine,
    if_exists='append',
    index=False
)